%% Load annotations and connectors

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;

%exclude unilateral ORNs for now

ORNs=[ORNs_Left, ORNs_Right];

%return all skeleton IDs of DM6 PNs
PNs=annotations.DM6_0x20_PN;

%% Calculate Path length

load('~/Documents/MATLAB/tracingCode2/currentWfly1ManuscriptFigures/ornOutputSynDensity/leftAxons')
load('~/Documents/MATLAB/tracingCode2/currentWfly1ManuscriptFigures/ornOutputSynDensity/rightAxons')


% For each ORN calculate its total ipsi within glomerulus length

for p=1:length(ORNs)
    
    leftRunL=[];
    leftRunPS=[];
    
    
    for j=1:size(leftAxons{p},2)
        
        leftRunL=[leftRunL, leftAxons{p}(1,j)];
        leftRunPS=[leftRunPS,leftAxons{p}(2,j)];
        
    end
    
    leftLengths(p)=sum(leftRunL);
    leftPreSites(p)=sum(leftRunPS);
    
    
    rightRunL=[];
    rightRunPS=[];
    
    
    for j=1:size(rightAxons{p},2)
        rightRunL=[rightRunL, rightAxons{p}(1,j)];
        rightRunPS=[rightRunPS,rightAxons{p}(2,j)];
    end
    
    rightLengths(p)=sum(rightRunL);
    rightPreSites(p)=sum(rightRunPS);
    
end


%% create array of length and Density for ipsi and Contra axons


ipsiLenDens(:,1)=[leftLengths(1:27),rightLengths(28:end)];
ipsiLenDens(:,2)=[leftPreSites(1:27)./leftLengths(1:27),rightPreSites(28:end)./rightLengths(28:end)];

contraLenDens(:,1)=[leftLengths(28:end),rightLengths(1:27)];
contraLenDens(:,2)=[leftPreSites(28:end)./leftLengths(28:end),rightPreSites(1:27)./rightLengths(1:27)];

%% Plotting
figure()

set(gcf,'Color','w')
subplot(1,2,1)
boxplot([ipsiLenDens(:,1),contraLenDens(:,1)])
ax=gca;
ax.XTickLabel={'ipsi axons','contra axons'};
ylabel('cable length(nm)');



subplot(1,2,2)
boxplot([ipsiLenDens(:,2),contraLenDens(:,2)])
ax=gca;
ax.XTickLabel={'ipsi axons','contra axons'};
ylabel('tbar density (tbars/nm)');

saveas(gcf,'ipsiContraLenDens')

