%scatterplot with one point per ORN showing total synapses formed onto PNs 
%in the ipsi glomerulus versus total synapses formed onto PNs in the contra 
%glomerulus (test for significance of ipsi/contra bias)

%Load ORN to PN contact number data, generated by file panel6_unitaryContNums
%in Figure 1 directory

load('~/Dropbox/htem_team/code/wtobin/tracingCode2/wfly1_Manuscript/Figure1/ornToPn.mat')

%loop over ORNs counting synapses onto ipsi and contra PNs. Currently, the first 25
%ORNs are L and the 2nd 25 R

% 150108 WCL: first 26 are L and 2nd 25 are R
for o=1:size(ornToPn,1)
    
    if o <= 26
        
        ipsiCont(o)=sum(ornToPn(o,[1,2,5]));
        contraCont(o)=sum(ornToPn(o,[3,4]));
        
    else
        
        ipsiCont(o)=sum(ornToPn(o,[3,4]));
        contraCont(o)=sum(ornToPn(o,[1,2,5]));
        
    end
end
        

%% Plotting


figure()
scatter(ipsiCont, contraCont)
set(gcf, 'Color', 'w')
ax=gca;
ax.XTick=[0:10:110];
ax.YTick=[0:10:110];
xlim([0 110]);
ylim([0 110]);
ax.FontSize=16;
refline(1,0)
xlabel('Num Ipsi PN Contacts', 'FontSize', 16);
ylabel('Num Cont PN Contacts', 'FontSize', 16);
title('Ipsi/Contra ORN-->PN Contact Nums ', 'FontSize', 16);

axis square

%% simple bars
gps = [ones(size(ipsiCont)),2.*ones(size(contraCont))];
vals = [ipsiCont,contraCont];
[Ymean,Ysem,Ystd,Yci] = grpstats(vals,gps,{'mean','sem','std','meanci'});

figure
bar([mean(ipsiCont),mean(contraCont)],.4,'FaceColor','k','LineWidth',2)
hold on
he = errorbar(Ymean,Ysem,'k','LineStyle','none'); % error bars are std
he.LineWidth=1;
xlim([0.5 2.5])
ylim([0 80])
ax = gca;
ax.XTick = [1 2];
ax.XTickLabel = {'Ipsi';'Contra'};
ylabel('Synapses')
axis square

%% plot pairs and bars
figure()
plot([1 2],[ipsiCont',contraCont'],'-o','Color',[0.67,0.67,0.67])
hold on
bar([mean(ipsiCont),mean(contraCont)],.4,'FaceColor','none','LineWidth',2)
xlim([0.5 2.5])
ylim([0 120])
ax = gca;
ax.XTick = [1 2];
ax.XTickLabel = {'Ipsi';'Contra'};
ylabel('ORN-->PN Synapses')
axis square

%% plot pairs, means, std

gps = [ones(size(ipsiCont)),2.*ones(size(contraCont))];
vals = [ipsiCont,contraCont];
[Ymean,Ysem,Ystd,Yci] = grpstats(vals,gps,{'mean','sem','std','meanci'});
%
figure()
plot([1 2],[ipsiCont',contraCont'],'-o','Color',[0.67,0.67,0.67])
hold on
plot(Ymean(1),'o','LineWidth',2,'MarkerSize',10,'MarkerEdgeColor','k')
plot(2,Ymean(2),'o','LineWidth',2,'MarkerSize',10,'MarkerEdgeColor','r')
he1=errorbar(1,Ymean(1),Ystd(1),'k','LineStyle','none') % error bars are std
he2=errorbar(2,Ymean(2),Ystd(2),'r','LineStyle','none')
he1.LineWidth=2;
he2.LineWidth=2;
xlim([0.5 2.5])
ylim([0 120])
ax = gca;
ax.XTick = [1 2];
ax.XTickLabel = {'Ipsi';'Contra'};

ylabel('ORN-->PN Synapses')

axis square
%% plot pairs, box plot

gps = [ones(size(ipsiCont)),2.*ones(size(contraCont))];
vals = [ipsiCont,contraCont];
[Ymean,Ysem,Ystd,Yci] = grpstats(vals,gps,{'mean','sem','std','meanci'});
%
figure()
plot([1 2],[ipsiCont',contraCont'],'-o','Color',[0.67,0.67,0.67])
hold on
h = boxplot(vals,gps,'notch','on');
h.LineWidth = 2;
xlim([0.5 2.5])
ylim([0 120])
ax = gca;
ax.XTick = [1 2];
ax.XTickLabel = {'Ipsi';'Contra'};

ylabel('ORN-->PN Synapses')

axis square
%% Permutation test (p~0)
nPerm = 100000;

sa = ipsiCont';
sb = contraCont';

sh0 = [sa; sb];

m = length(sa); 
n = length(sb); 

d_empirical = mean(sa) - mean(sb);

sa_rand = zeros(m,nPerm);
sb_rand = zeros(n,nPerm);
tic
for ii = 1:nPerm
    sa_rand(:,ii) = randsample(sh0,m);%,true);
    sb_rand(:,ii) = randsample(sh0,n);%,true);
end
toc
% Now we compute the differences between the means of these resampled
% samples.
% d = median(sb_rand) - median(sa_rand);
d = mean(sa_rand) - mean(sb_rand);

%
figure;
% [nn,xx] = hist(d,100);
% bar(xx,nn/sum(nn))
histogram(d,'Normalization','probability')
ylabel('Probability of occurrence')
xlabel('Difference between means')
hold on
%

y = get(gca,'yLim'); % y(2) is the maximum value on the y-axis.
x = get(gca,'xLim'); % x(1) is the minimum value on the x-axis.
plot([d_empirical,d_empirical],y*.99,'r-','lineWidth',2)

% Probability of H0 being true = 
% (# randomly obtained values > observed value)/total number of simulations
p = sum(abs(d) > abs(d_empirical))/length(d);
text(x(1)+(.01*(abs(x(1))+abs(x(2)))),y(2)*.95,sprintf('H0 is true with %4.4f probability.',p))

%% A further thought


ipsiInputCVs=[std(ornToPn(1:25,[5,1,2]))./mean(ornToPn(1:25,[5,1,2])),...
std(ornToPn(26:end,[3,4]))./mean(ornToPn(26:end,[3,4]))]


contraInputCVs=[std(ornToPn(26:end,[5,1,2]))./mean(ornToPn(26:end,[5,1,2])),...
std(ornToPn(1:25,[3,4]))./mean(ornToPn(1:25,[3,4]))]


figure()
set(gcf,'Color', 'w')
scatter(ipsiInputCVs(1:3),contraInputCVs(1:3), 'filled')
hold on
scatter(ipsiInputCVs([4,5]),contraInputCVs([4,5]), 'r', 'filled')


xlim([.2 .36])
ylim([.2 .36])
refline(1,0)
xlabel('Ipsi ORN Contact Num CV', 'FontSize', 16)

ylabel('Contra ORN Contact Num CV', 'FontSize', 16)

    

ipsiInputSTDs=[std(ornToPn(1:25,[5,1,2])),...
std(ornToPn(26:end,[3,4]))]


contraInputSTDs=[std(ornToPn(26:end,[5,1,2])),...
std(ornToPn(1:25,[3,4]))]


figure()
set(gcf,'Color', 'w')
scatter(ipsiInputSTDs(1:3),contraInputSTDs(1:3), 'filled')
hold on
scatter(ipsiInputSTDs([4,5]),contraInputSTDs([4,5]), 'r', 'filled')


xlim([3.5 10])
ylim([3.5 10])
refline(1,0)
xlabel('Ipsi ORN Contact Num STD', 'FontSize', 16)

ylabel('Contra ORN Contact Num STD', 'FontSize', 16)


%% Plotting for lab meeting fraction of ORN contacts from ipsi vs contra ORNs


    
for o=1:size(ornToPn,2)
    
    if o <= 
        
        ipsiCont(o)=sum(ornToPn(o,[1,2,5]));
        contraCont(o)=sum(ornToPn(o,[3,4]));
        
    else
        
        ipsiCont(o)=sum(ornToPn(o,[3,4]));
        contraCont(o)=sum(ornToPn(o,[1,2,5]));
        
    end
end
        
    
    