%scatterplot with one point per ORN showing total synapses formed onto PNs 
%in the ipsi glomerulus versus total synapses formed onto PNs in the contra 
%glomerulus (test for significance of ipsi/contra bias)

%Load ORN to PN contact number data, generated by file panel6_unitaryContNums
%in Figure 1 directory

load('~/Documents/MATLAB/tracingCode2/wfly1_Manuscript/ornToPn.mat')

%loop over ORNs counting synapses onto ipsi and contra PNs. Currently, the first 25
%ORNs are L and the 2nd 25 R

for o=1:size(ornToPn,1)
    
    if o <= 25
        
        ipsiCont(o)=sum(ornToPn(o,[1,2,5]));
        contraCont(o)=sum(ornToPn(o,[3,4]));
        
    else
        
        ipsiCont(o)=sum(ornToPn(o,[3,4]));
        contraCont(o)=sum(ornToPn(o,[1,2,5]));
        
    end
end
        

%% Plotting


figure()
scatter(ipsiCont, contraCont)
set(gcf, 'Color', 'w')
ax=gca;
ax.XTick=[0:10:110];
ax.YTick=[0:10:110];
xlim([0 110]);
ylim([0 110]);
ax.FontSize=16;
refline(1,0)
xlabel('Num Ipsi PN Contacts', 'FontSize', 16);
ylabel('Num Cont PN Contacts', 'FontSize', 16);
title('Ipsi/Contra ORN-->PN Contact Nums ', 'FontSize', 16);
    
    