%% This script is written to record each simulated mEPSP at the site of the synapse

% 1. Loop over each contact

% 2. modify the .hoc file to put the recording electrode at the synapse

% 3. save spike vector files causing only that synapse to fire once

% 4. run the simulation

% 5. load the result and save it



%% Step 0 load annotations

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;


ORNs=[ORNs_Left, ORNs_Right];



PN_Names={'PN1LS','PN2LS', 'PN3LS', 'PN1RS', 'PN2RS'};

%% Step 1 File handling


% make a copy of the original generatedNEURON directory and call it
% localMini

for p=1:length(PN_Names)
    
    PN=PN_Names{p};
    
    % Move to the current PNs directory within the nC_Projects dir
    % Path structure for my Ubuntu machine
    cd(['/home/simulation/nC_projects/', PN, '_allORNs/']);
    
    % First things first, I need to make simulation directory for localMini
    % sims
    system('mkdir simulations/localMinis')
    cd('simulations/localMinis/')
    
    %copy the contents of generatedNEURON to this directory
    system('cp -R ../../generatedNEURON/* ./')


% I want to run Wei's script to copy/compile VecEvent.mod in each
% PN_allORNs/generatedNEURON dir. Also run hocEdsv_WTMod.py on each PN.hoc
% file


    % copy vecEvent.mod to the cur dir and compile it
    vecEventcmd='bash ../../../copy_comp.sh';
    system(vecEventcmd);
    
    %run hocEdsv.py on the PN_allORNs.hocfile in the cur dir. 
    
    hocModcmd=['python ../../../hocEdsv2.py ', PN ,'_allORNs.hoc ', PN, '_allORNs'];
    system(hocModcmd)
    
    %This code fragment is for use on the simulation machine only, it
    %changes paths in hoc file from /william/ to /simulation/
       % Change the simReference = line in the hoc file and simsDir
    simPatCmd=['sed -i -e ''s/\/home\/william\//\/home\/simulation\//'' ',PN, '_allORNs.hoc'];
    system(simPatCmd)
    
    % Change the simReference = line in the hoc file and simsDir
    simName='localMinis';
    simRefCmd=['sed -i -e ''s/simReference\s\=\s\".*\"/simReference \= \"',simName,'\"/'' ',PN, '_allORNs.hoc'];
    system(simRefCmd)
    
    simDir=['/home/simulation/nC_projects/',PN,'_allORNs/simulations/'];
    simRefCmd=['sed -i -e ''s#simsDir\s\=\s\".*\"#simsDir \= \"',simDir,'\"#'' ',PN, '_allORNs.hoc'];
    system(simRefCmd)
    
    %Set initial Vm
    initVm=-60; %in mv
    runVCmd=['sed -i -e ''s#v\s\=\s\-65\.\0#v = \',num2str(initVm),'#'' ',PN, '_allORNs.hoc'];
    system(runVCmd)
    
    
     %Setsim duration
    runTime=250; %in ms
    runTCmd=['sed -i -e ''s#tstop\s\=\s.*#tstop \= ',num2str(runTime),'#'' ',PN, '_allORNs.hoc'];
    system(runTCmd)
    
 
    
end

%% Loop over each contact in each PN

for p=1:length(PN_Names)
    
    
    PN=PN_Names{p};
    
    % Move to the current PNs localMini/generatedNEURON dir
    cd(['/home/simulation/nC_projects/',PN,'_allORNs/simulations/localMinis/']);
    
    %make a backup copy of the hoc file
    bkCmd=['cp ', PN,'_allORNs.hoc ', PN,'_allORNs.hoc.bak2'];
    system(bkCmd);
    
    
    %make a spike Vector directory
    system('mkdir ../../spikeVectors')
    
    %Identify the PN skeleton ID
    skelIDCmd=['grep -o -P ''\&a_neuron_PN\d_\SS_sk_\K\d*'' ',PN, '_allORNs.hoc' ];
    [status, workingSkelID ]=system(skelIDCmd);
    
    %find the vector file number each contact looks to for its activity
    vecFileCmd=['grep -oP ''\[\d*\].ropen\("/home/simulation/nC_projects/',PN,'_allORNs/spikeVectors/spikeVector\K\d*'' ' , PN,'_allORNs.hoc'];
    [status, vecFileNums]=system(vecFileCmd);
    vecFileNums=str2num(vecFileNums);
    
    
    % find each contacts compartment
    compNumCmd=['grep -oP ''access a_neuron_PN.*\[\d*\]\.c\K\d*'' ' , PN,'_allORNs.hoc'];
    [status, compartNums]=system(compNumCmd);
    compartNums=str2num(compartNums);
    
    % find each contacts position within the compartment
    compPosCmd=['grep -oP ''new DoubExpSynA\(0.\K\d*'' ' , PN,'_allORNs.hoc'];
    [status, compartPos]=system(compPosCmd);
    compartPos=str2num(compartPos);
    
    % make sure all of these vectors have the same number of elements.
    % System calls in matlab have a bug whereby the output is often
    % truncated
    
    while numel(vecFileNums) ~= numel(compartNums) || numel(vecFileNums) ~= numel(compartPos) || numel(compartNums) ~= numel(compartPos)
        
        clear compartPos vecFileNums compartNums
        
        [status, vecFileNums]=system(vecFileCmd);
        vecFileNums=str2num(vecFileNums);
        
        [status, compartNums]=system(compNumCmd);
        compartNums=str2num(compartNums);

        [status, compartPos]=system(compPosCmd);
        compartPos=str2num(compartPos);
        
        
    end
    
    

    for s=1:numel(vecFileNums)
        tic
        %restore original file
        restoreCmd=['cp -f ',PN, '_allORNs.hoc.bak2 ', PN, '_allORNs.hoc'];
        system(restoreCmd);
        
        % move my simulated electrode to the site of the working contact
        
        mvElecCmd=['sed -i ''s#\&a_neuron_PN.*_.*S_sk_.*\[i\]\.c.*\.v[(]0\..*[)]#\&a_neuron_',...
            PN(1:3),'_',PN(4:5),'_sk_',num2str(workingSkelID(1:6)),'[i].c',...
            num2str(compartNums(s)),'.v(0.',num2str(compartPos(s)),'))#'' ' ,PN, '_allORNs.hoc' ];
        
        system(mvElecCmd);
        
        % plot voltage for this pos as well
        
        chngPlotCmd1=['sed -i ''s#\.c2\.v[(]0\.5[)]#\.c',...
            num2str(compartNums(s)),'.v(0.',num2str(compartPos(s)),')#'' ' ,PN, '_allORNs.hoc' ];
        
        system(chngPlotCmd1);
        
        chngPlotCmd2=['sed -i ''s#\.c2\.v#\.c',...
            num2str(compartNums(s)),'.v#'' ' ,PN, '_allORNs.hoc' ];
        
        system(chngPlotCmd2);
        
        
        %save spike vector files which are empty for all but the active
        %contact and put a single spike in that file at 10ms
        
        saveSpikeVectors(vecFileNums,[vecFileNums(s) 1],{10},['/home/simulation/nC_projects/',PN,'_allORNs/spikeVectors']);
        
        
         
            %I want to run the simulation
            
            runCmd=['nrniv ', PN, '_allORNs.hoc'];
            system(runCmd);
            
            
            %I want to import the PNs simulated voltage trace
            
            
            %find its name
            pnResults=dir('neuron_PN*.dat');
            
            pnVm1=importdata(pnResults.name);
            
            localMinis{p}(s,:)=pnVm1;
            
       toc 
    end
    
    dlmwrite('vecFiles',vecFileNums)
    dlmwrite('compartmentNums',compartNums)
    dlmwrite('compartPos',compartPos)
    
end 

cd('../../../')
save('localMinis','localMinis')

%% some plotting

for p=1:5
    
    for a=1:size(localMinis{p},1)
        
        miniAmps{p}(a)=max(localMinis{p}(a,:))-mean(localMinis{p}(a,1:399));
        
    end
    
  
end

figure()
set(gcf, 'Color', 'w')

for i=1:5
    subplot(5,1,i)
%     scatter(i*ones(1,numel(miniAmps{i})),miniAmps{i})
%     
%     hold on

hist(miniAmps{i},100)
xlim([0 10])
title(PN_Names(i),'FontSize',12)

if i==5
    
    xlabel('local mini amp (mv)','FontSize',16)
    ylabel('Freq','FontSize',16)
    
else
end

end

