%% the goal of this code is to test whether the ORN--PN contact number dist is more or less uniformly distributed than random

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;

%exclude unilateral ORNs for now

ORNs_Right(find(ORNs_Right == 499879))=[];
ORNs_Left(find(ORNs_Left == 426230))=[];
ORNs_Left(find(ORNs_Left == 401378))=[];

%return all skeleton IDs of DM6 PNs
PNs=annotations.PN;

% Loop over PNs

for p=1:length(PNs)
    
    
    % find the number of inputs it receives from Right ORNs
    for j=1:length(ORNs_Right)
        
        numContactsRORNs(p,j)=getSynapseNum(ORNs_Right(j), PNs(p));
    end
    
    % find the number of inputs it receives from Left ORNs
    for j=1:length(ORNs_Left)
        
        numContactsLORNs(p,j)=getSynapseNum(ORNs_Left(j), PNs(p));
    end
    
    
    %loop over number of simulations
    for s=1:1000
        tic
        % Randomly assign R synapses to a pop of fictive ORNs
        
        for n=1:sum(numContactsRORNs(p,:))
            
            rndContactsR{p}(s,n)=randi(length(ORNs_Right));
        end
    
        % Randomly assign L synapses to a pop of fictive ORNs
        
        for n=1:sum(numContactsLORNs(p,:))
            
            rndContactsL{p}(s,n)=randi(length(ORNs_Left));
            
        end
        toc
    end
        
    
    


