%{
Ok some pseudocode

1. Create list of the left and right ORNs for which i have measured synapse
size

2. Copy all connectorID_initials.nii segmention files to a single directory

3. For each ORN-PN pair, Search through the connector list and at each
connector where the cells are connected, pull the tbar volume and
postsynaptic membrane area. Store these measures in an array thats like
array(orn,pn,1)=tbarArea array(orn, p,2)=membrane area

4. Compare ipsi/contra, left right sizes and test significance





%}


%% make lists of ORNs and PNs that have been segmented, load conn list

leftORNSubset=[337396,401197,492811,320688,699676];
rightORNSubset=[360235,362982,332797,379044,362999];

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

%return all skeleton IDs of DM6 PNs
PNs=sort(annotations.DM6_0x20_PN);

%Load the connector structure
load('~/tracing/conns.mat')

%gen conn fieldname list
connFields=fieldnames(conns);

%%
%{
For each ORN-PN pair, Search through the connector list and at each
connector where the cells are connected, pull the tbar volume and
postsynaptic membrane area. Store these measures in an array thats like
array(orn,pn,1)=tbarArea array(orn, p,2)=membrane area
%}

tbarLabel=6;
basePath='/Users/williamtobin/Desktop/wfly1_synapseVols2/segFiles/';
pixelNums=[];

Users={'JK','HY','BS','WC'};

for u=1:4
    
    ornCounter=0;
    
    for o = [leftORNSubset, rightORNSubset]
        tic
        ornCounter=ornCounter+1;
        pnCounter=0;
        
        for p = PNs
            pnCounter=pnCounter+1;
            
            if p == 427345
                postLabel=1;
            elseif p == 419138
                postLabel=2;
            elseif p ==668267
                postLabel=3;
            elseif p==480245
                postLabel=4;
            elseif p==638603
                postLabel=5;
            end
            
            synCounter=0;
            
            for curField = 1:length(connFields)
                
                c=connFields(curField);
                connID=cell2mat(c);
                connID=connID([5,7:length(connID)]);
                pre=conns.(cell2mat(c)).pre;
                post=conns.(cell2mat(c)).post;
                
                
                if isempty(pre)==1
                else
                    if pre == o && ismember(p,post)==1
                        curSegFileDir=dir([basePath,connID,'_**.nii']);
                        
                        
                        if isempty(curSegFileDir)==1
                        else
                            for f =1:length(curSegFileDir)
                                
                                if sum(curSegFileDir(f).name(end-5:end-4)==Users{u})==2
                                    
                                    curSegFile=load_nii([basePath, curSegFileDir(f).name]);

                                    synCounter=synCounter+1;
                                    
                                    pixelNums{u}{ornCounter}{pnCounter}(synCounter,1)=numel(curSegFile.img(curSegFile.img==tbarLabel));
                                    pixelNums{u}{ornCounter}{pnCounter}(synCounter,2)=numel(curSegFile.img(curSegFile.img==postLabel));
                                    
                                else
                                end
                            end
                        end
                    end
                    
                end
            end
        end
        
        
      toc  
    end
    
    
end


%% Some sorting ipsi contra



f1=figure();
f2=figure();

for u=1:4
    
    ipsiTbarPx=[];
    contraTbarPx=[];
    
    ipsiPost=[];
    contraPost=[];
    
    
    for o=1:10
        
        curO=pixelNums{u}{o};
        
        if isempty(curO)==1
        else
            
            for p=1:length(curO)
                
                curOP=curO{p};
                
                if isempty(curOP)==1
                else
                    
                    if o<=5 && ismember(p,[1,2,5])==1
                        
                        ipsiTbarPx=[ipsiTbarPx;curOP(:,1)];
                        ipsiPost=[ipsiPost;curOP(:,2)];
                        
                    elseif o<=5 && ismember(p,[1,2,5])==0
                        
                        contraTbarPx=[contraTbarPx;curOP(:,1)];
                        contraPost=[contraPost;curOP(:,2)];
                        
                    elseif o>5 && ismember(p,[1,2,5])==1
                        
                        contraTbarPx=[contraTbarPx;curOP(:,1)];
                        contraPost=[contraPost;curOP(:,2)];
                        
                    elseif o>5 && ismember(p,[1,2,5])==0
                        
                        ipsiTbarPx=[ipsiTbarPx;curOP(:,1)];
                        ipsiPost=[ipsiPost;curOP(:,2)];
                    end
                end
            end
        end
    end
    
    figure(f1)
    
    [p,h]=ranksum(ipsiTbarPx,contraTbarPx);
    subplot(2,2,u)
    hold on
    histogram(ipsiTbarPx,50)
    histogram(contraTbarPx,50)
    title(['Tracer ',num2str(u), ' Wilcoxon rank sum p: ',num2str(p)])
    xlabel('Number of Pixels/Tbar','FontSize',14)
    ylabel('Freq','FontSize',14)
    legend({'Ipsilateral Tbars';'Contralateral Tbars'})
    %text(
    
    
    figure(f2)
    subplot(2,2,u)
    hold on
    histogram(ipsiPost,500)
    histogram(contraPost,500)
    xlim([0 500])
    title(['Tracer ',num2str(u)])
    xlabel('Number of Pixels/Postsynaptic PN','FontSize',14)
    ylabel('Freq','FontSize',14)
    legend({'Ipsilateral PNs';'Contralateral PNs'})
    
end

%% Some sorting left/right


f1=figure();
f2=figure();


for u=1:4

rightTbarPx=[];
leftTbarPx=[];

rightPost=[];
leftPost=[];

for o=1:10
    
    curO=pixelNums{u}{o};
    
    if isempty(curO)==1
    else
        
        for p=1:length(curO)
            
            curOP=curO{p};
            
            if isempty(curOP)==1
            else
                
                if ismember(p,[1,2,5])==1
                    
                    leftTbarPx=[leftTbarPx;curOP(:,1)];
                    leftPost=[leftPost;curOP(:,2)];
                    
                elseif ismember(p,[3,4])==1
                    
                    rightTbarPx=[rightTbarPx;curOP(:,1)];
                    rightPost=[rightPost;curOP(:,2)];
                    
                    
                end
            end
        end
    end
end


    figure(f1)
    subplot(2,2,u)
    hold on
    histogram(rightTbarPx,50)
    histogram(leftTbarPx,50)
    title(['Tracer ',num2str(u)])
    xlabel('Number of Pixels/Tbar','FontSize',14)
    ylabel('Freq','FontSize',14)
    legend({'Right Tbars';'Left Tbars'})
    
    figure(f2)
    subplot(2,2,u)
    hold on
    histogram(rightPost,500)
    histogram(leftPost,500)
    xlim([0 500])
    title(['Tracer ',num2str(u)])
    xlabel('Number of Pixels/Postsynaptic PN','FontSize',14)
    ylabel('Freq','FontSize',14)
    legend({'Right PNs';'Left PNs'})
    


end


%% Some sorting ipsi contra

ipsiTbarPxMeans=[];
contraTbarPxMeans=[];

ipsiPostMeans=[];
contraPostMeans=[];

for u=1:4
    
    U=pixelNums{u};

for o=1:10
    
    curO=U{o};
    
    if isempty(curO)==1
    else
        
        for p=1:length(curO)
            
            curOP=curO{p};
            
            if isempty(curOP)==1
            else
                
                if o<=5 && ismember(p,[1,2,5])==1
                    
                    ipsiTbarPxMeans=[ipsiTbarPxMeans;mean(curOP(:,1))];
                    ipsiPostMeans=[ipsiPostMeans;mean(curOP(:,2))];
                    
                elseif o<=5 && ismember(p,[1,2,5])==0
                    
                    contraTbarPxMeans=[contraTbarPxMeans;mean(curOP(:,1))];
                    contraPostMeans=[contraPostMeans;mean(curOP(:,2))];
                    
                elseif o>5 && ismember(p,[1,2,5])==1
                    
                    contraTbarPxMeans=[contraTbarPxMeans;mean(curOP(:,1))];
                    contraPostMeans=[contraPostMeans;mean(curOP(:,2))];
                    
                elseif o>5 && ismember(p,[1,2,5]) == 0
                    
                    ipsiTbarPxMeans=[ipsiTbarPxMeans;mean(curOP(:,1))];
                    ipsiPostMeans=[ipsiPostMeans;mean(curOP(:,2))];
                    
                end
            end
        end
    end
end

CV_tbar=std(ipsiTbarPxMeans)/mean(ipsiTbarPxMeans)
%CV_post=std(ipsiPostMeans)/mean(ipsiPostMeans)
end

%% Scratch

figure()
counter=1;
for o=1:5
    for p=[3,4]
        
        subplot(2,5,counter)
        counter=counter+1
        histogram(pixelNums{o}{p}(:,1),20)
        xlim([0 4000])
        
        
    end
    
    
    
end

%%

o=337396;

p=427345;

counter=0;

for c =1:length(connFields)
    
    connField=cell2mat(connFields(c));
    conn=conns.(connField);
    if isempty(conn.pre)==1
    else
        
        if conn.pre == o && ismember(p,conn.post)==1
            
            
            counter=counter+sum(conn.post==p)
            
        else
        end
    end
    
    
end
