%% Boxplot showing number of inputs received by each PN from ipsi and contra ORNs

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;

%exclude unilateral ORNs for now

ORNs_Right(find(ORNs_Right == 499879))=[];
ORNs_Left(find(ORNs_Left == 426230))=[];
ORNs_Left(find(ORNs_Left == 401378))=[];
% 
% %exclude ORN 8 because it was temporarily unilateral on 8/5 for testing 
% ORNs_Left(find(ORNs_Left == 593865))=[];
% 


%return all skeleton IDs of DM6 PNs
PNs=annotations.PN;

% For each PN
for i=1:5
    
    
    % find the number of inputs it receives from Right ORNs
    for j=1:length(ORNs_Right)
        
        numContactsRORNs(i,j)=getSynapseNum(ORNs_Right(j), PNs(i));
    end
    
    % And the number of inputs it receives from Left ORNs
    for j=1:length(ORNs_Left)
        
        numContactsLORNs(i,j)=getSynapseNum(ORNs_Left(j), PNs(i));
        
    end
    
end

%Boxplot these values

titles={'PN3 LS', 'PN2 LS', 'PN1 RS', 'PN2 RS', 'PN1 LS'};

for i=1:length(PNs)
    
    
    subplot(2,3,i)
    
    boxplot([numContactsLORNs(i,:),numContactsRORNs(i,:)],[zeros(1,length(numContactsLORNs(i,:))),ones(1,length(numContactsRORNs(i,:)))], 'notch', 'on')
    set(gca,'XTickLabel',['Left ORNs ';'Right ORNs'])
    ylabel('Num of Contacts')
    title(titles(i))
    set(gcf,'color','w');
    
end


%scatter plot these values


titles={'PN3 LS', 'PN2 LS', 'PN1 RS', 'PN2 RS', 'PN1 LS'};

counter=1;
for i=1:5
    
    for j=1:5
        
        subplot(5,5,counter)
        
        scatter(numContactsLORNs(i,:),numContactsLORNs(j,:))
        hold on
        scatter(numContactsRORNs(i,:),numContactsRORNs(j,:), 'r')
        
        
        counter=counter+1;
        xlabel(titles(i))
        ylabel(titles(j))
        
    end
    
end

%% Plot the total number of synapses made by each ORN on to R v L hemishere PNs

for i =1:length(numContactsLORNs)
    
    leftORN_sums(i,1)=sum(numContactsLORNs([1,2,5],i));
    leftORN_sums(i,2)=sum(numContactsLORNs([3,4],i));
end

subplot(1,2,1)
scatter(leftORN_sums(:,1), leftORN_sums(:,2))
xlabel('Num Conns onto L PNs') 
ylabel('Num Conns onto R PNs') 
title('Left ORNs')

for i =1:length(numContactsRORNs)
    
    rightORN_sums(i,1)=sum(numContactsRORNs([1,2,5],i));
    rightORN_sums(i,2)=sum(numContactsRORNs([3,4],i));
end

subplot(1,2,2)
scatter(rightORN_sums(:,1), rightORN_sums(:,2))

xlabel('Num Conns onto L PNs') 
ylabel('Num Conns onto R PNs') 
title('Right ORNs')

%% Hist of number of ORN output synapses 


%Load the connector structure
load('~/tracing/conns.mat')

%gen conn fieldname list
connFields=fieldnames(conns);

% Loop over L ORNs
for o=1:length(ORNs_Left)
    
synCounter=0;

%loop over all connectors
for i= 1 : length(connFields)
    
    %Make sure the connector doesnt have an empty presynaptic field
    if isempty(conns.(cell2mat(connFields(i))).pre) == 1
        
    else
        
        %Check to see if the working skel is presynaptic at this connector
        if conns.(cell2mat(connFields(i))).pre == ORNs_Left(o)


                synCounter=synCounter+1;
                
          
        else
        end
    end
end

sumLeftORNOuts(o)=synCounter;

end


% Loop over R ORNs
for o=1:length(ORNs_Right)
    
synCounter=0;

%loop over all connectors
for i= 1 : length(connFields)
    
    %Make sure the connector doesnt have an empty presynaptic field
    if isempty(conns.(cell2mat(connFields(i))).pre) == 1
        
    else
        
        %Check to see if the working skel is presynaptic at this connector
        if conns.(cell2mat(connFields(i))).pre == ORNs_Right(o)


                synCounter=synCounter+1;
                
          
        else
        end
    end
end

sumRightORNOuts(o)=synCounter;

end

figure()
set(gcf, 'color', 'w')

subplot(1,2,1)
hist(sumLeftORNOuts, 20)
xlabel('Num Output Synapses')
ylabel('Freq')
title('Left ORNs')
xlim([40 110])


subplot(1,2,2)
hist(sumRightORNOuts, 20)
xlabel('Num Output Synapses')
ylabel('Freq')
title('Right ORNs')
xlim([40 110])

