%% this script is written to pull all PN skeleton node radii


% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');


%return all skeleton IDs of DM6 PNs
PNs=annotations.DM6_0x20_PN;


for p=1:5
    
   
workingSkel=loadjson(['~/tracing/skeletons/',num2str(PNs(p)),'.json']);

vertFields=fieldnames(workingSkel.vertices);
  tic  
for v=1:numel(vertFields)
    
    if strcmp(workingSkel.vertices.(cell2mat(vertFields(v))).type,'skeleton')==1
    radii{p}(v)=workingSkel.vertices.(cell2mat(vertFields(v))).radius;
    
    else
    end
    
end

perIncom(p)=sum(radii{p}==-1);




toc
end


%% plotting

figure()
set(gcf, 'Color', 'w')

PN_Names={'PN1LS','PN2LS', 'PN3LS', 'PN1RS', 'PN2RS'};

for i=1:5
    subplot(5,1,i)
%     scatter(i*ones(1,numel(miniAmps{i})),miniAmps{i})
%     
%     hold on

hist(radii{i},250)
 xlim([0 200])
title(PN_Names(i),'FontSize',12)

if i==5
    
    xlabel('node radii (mv)','FontSize',16)
    ylabel('Freq','FontSize',16)
    
else
end



end



forBox=[];
for i=1:5
   
    meanRadius(i)=mean(radii{i});
    forBox_w(:,1)=radii{i};
    forBox_w(:,2)=i*ones(numel(radii{i}),1);
    forBox=[forBox;forBox_w];
    
    forBox_w=[];
end

figure()
set(gcf, 'Color', 'w')
boxplot(forBox(:,1),forBox(:,2))
ax=gca;
ax.XTickLabel=PN_Names;
ax.YLim=[-60 1000];
ylabel('Node Radius(nm)');
ax.FontSize=16;

