%% Load annotations and connectors

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('/home/simulation/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;

%exclude unilateral ORNs for now

ORNs_Right(find(ORNs_Right == 499879))=[];
ORNs_Left(find(ORNs_Left == 426230))=[];
ORNs_Left(find(ORNs_Left == 401378))=[];
% 
% %exclude ORN 8 because it was temporarily unilateral on 8/5 for testing 
% ORNs_Left(find(ORNs_Left == 593865))=[];

ORNs=[ORNs_Left, ORNs_Right];

%return all skeleton IDs of DM6 PNs
PNs=annotations.PN;

%return all LN skel IDs
LNs=annotations.LN;
LNs=[LNs, annotations.potential_0x20_LN];
% LNs=[LNs, annotations.Prospective_0x20_LN];
% LNs=[LNs, annotations.Likely_0x20_LN];


%Load the connector structure
load('/home/simulation/tracing/conns.mat')

%gen conn fieldname list
connFields=fieldnames(conns);

%% Collect simulation results for PN1LS

pn1LS_Vm=importdata('/home/simulation/nC_projects/PN1LS_151125/simulations/minis_151130/neuron_PN1_LS_sk_419138_0.dat');
pn1LS_simTime=importdata('/home/simulation/nC_projects/PN1LS_151125/simulations/minis_151130/time.dat');

%collect ORN skel IDs from PN1LS hoc file, one for every synapse,  and save them in a txt file
idCommand='grep -Po ''(?<=^synapse_)\d*'' /home/simulation/nC_projects/PN1LS_151125/simulations/minis_151130/PN1LS_151125.hoc > /home/simulation/nC_projects/PN1LS_151125/simulations/minis_151130/synapseIDs.txt ';
system(idCommand);
synIDs=importdata('/home/simulation/nC_projects/PN1LS_151125/simulations/minis_151130/synapseIDs.txt');

fireTimeCmd='grep -Po ''((?<=.start = )\d*)'' /home/simulation/nC_projects/PN1LS_151125/simulations/minis_151130/PN1LS_151125.hoc > /home/simulation/nC_projects/PN1LS_151125/simulations/minis_151130/ornSpikeTimes.txt';
system(fireTimeCmd);
fireTimes=importdata('/home/simulation/nC_projects/PN1LS_151125/simulations/minis_151130/ornSpikeTimes.txt');


%% Collect mEPSPs in an array



for o=1:length(synIDs)
    
    somaMini=pn1LS_Vm(find(pn1LS_simTime==fireTimes(o))-40:find(pn1LS_simTime==fireTimes(o))+1000);
    
    somaOverLocal{1}(o)=(max(somaMini)+59.4)/(max(localMinis{1}(o,:))+59.4);
    
    
    
end

%% Collect simulation results for PN2LS

pn2LS_Vm=importdata('/home/simulation/nC_projects/PN2LS_151125/simulations/minis_151130/neuron_PN2_LS_sk_427345_0.dat');
pn2LS_simTime=importdata('/home/simulation/nC_projects/PN2LS_151125/simulations/minis_151130/time.dat');

%collect ORN skel IDs from PN1LS hoc file and save them in a txt file
idCommand='grep -Po ''(?<=^synapse_)\d*'' /home/simulation/nC_projects/PN2LS_151125/simulations/minis_151130/PN2LS_151125.hoc > /home/simulation/nC_projects/PN2LS_151125/simulations/minis_151130/ornIDs.txt ';
system(idCommand);
synIDs=importdata('/home/simulation/nC_projects/PN2LS_151125/simulations/minis_151130/ornIDs.txt');

fireTimeCmd='grep -Po ''((?<=.start = )\d*)'' /home/simulation/nC_projects/PN2LS_151125/simulations/minis_151130/PN2LS_151125.hoc > /home/simulation/nC_projects/PN2LS_151125/simulations/minis_151130/ornSpikeTimes.txt';
system(fireTimeCmd);
fireTimes=importdata('/home/simulation/nC_projects/PN2LS_151125/simulations/minis_151130/ornSpikeTimes.txt');


%% Collect MEPSPs in an array


for o=1:length(synIDs)
    
    somaMini=pn2LS_Vm(find(pn2LS_simTime==fireTimes(o))-40:find(pn2LS_simTime==fireTimes(o))+1000);
    
    somaOverLocal{2}(o)=(max(somaMini)+59.4)/(max(localMinis{2}(o,:))+59.4);
    
    
    
end


%% Collect simulation results for PN3LS

pn3LS_Vm=importdata('/home/simulation/nC_projects/PN3LS_151125/simulations/minis_151130/neuron_PN3_LS_sk_668267_0.dat');
pn3LS_simTime=importdata('/home/simulation/nC_projects/PN3LS_151125/simulations/minis_151130/time.dat');

%collect ORN skel IDs from PN1LS hoc file and save them in a txt file
idCommand='grep -Po ''(?<=^synapse_)\d*'' /home/simulation/nC_projects/PN3LS_151125/simulations/minis_151130/PN3LS_151125.hoc > /home/simulation/nC_projects/PN3LS_151125/simulations/minis_151130/ornIDs.txt ';
system(idCommand);
synIDs=importdata('/home/simulation/nC_projects/PN3LS_151125/simulations/minis_151130/ornIDs.txt');

fireTimeCmd='grep -Po ''((?<=.start = )\d*)'' /home/simulation/nC_projects/PN3LS_151125/simulations/minis_151130/PN3LS_151125.hoc > /home/simulation/nC_projects/PN3LS_151125/simulations/minis_151130/ornSpikeTimes.txt';
system(fireTimeCmd);
fireTimes=importdata('/home/simulation/nC_projects/PN3LS_151125/simulations/minis_151130/ornSpikeTimes.txt');


%% Collect MEPSPs in an array


for o=1:length(synIDs)
    
    somaMini=pn3LS_Vm(find(pn3LS_simTime==fireTimes(o))-40:find(pn3LS_simTime==fireTimes(o))+1000);
    
    somaOverLocal{3}(o)=(max(somaMini)+59.4)/(max(localMinis{3}(o,:))+59.4);
    
    
    
end

%% Collect simulation results for PN1RS

pn1RS_Vm=importdata('/home/simulation/nC_projects/PN1RS_151125/simulations/minis_151130/neuron_PN1_RS_sk_638603_0.dat');
pn1RS_simTime=importdata('/home/simulation/nC_projects/PN1RS_151125/simulations/minis_151130/time.dat');

%collect ORN skel IDs from PN1LS hoc file and save them in a txt file
idCommand='grep -Po ''(?<=^synapse_)\d*'' /home/simulation/nC_projects/PN1RS_151125/simulations/minis_151130/PN1RS_151125.hoc > /home/simulation/nC_projects/PN1RS_151125/simulations/minis_151130/ornIDs.txt ';
system(idCommand);
synIDs=importdata('/home/simulation/nC_projects/PN1RS_151125/simulations/minis_151130/ornIDs.txt');

fireTimeCmd='grep -Po ''((?<=.start = )\d*)'' /home/simulation/nC_projects/PN1RS_151125/simulations/minis_151130/PN1RS_151125.hoc > /home/simulation/nC_projects/PN1RS_151125/simulations/minis_151130/ornSpikeTimes.txt';
system(fireTimeCmd);
fireTimes=importdata('/home/simulation/nC_projects/PN1RS_151125/simulations/minis_151130/ornSpikeTimes.txt');


%% Collect MEPSPs in an array


for o=1:length(synIDs)
    
    somaMini=pn1RS_Vm(find(pn1RS_simTime==fireTimes(o))-40:find(pn1RS_simTime==fireTimes(o))+1000);
    
    somaOverLocal{4}(o)=(max(somaMini)+59.4)/(max(localMinis{4}(o,:))+59.4);
    
    
    
end
%% Collect simulation results for P2RS

pn2RS_Vm=importdata('/home/simulation/nC_projects/PN2RS_151125/simulations/minis_151130/neuron_PN2_RS_sk_480245_0.dat');
pn2RS_simTime=importdata('/home/simulation/nC_projects/PN2RS_151125/simulations/minis_151130/time.dat');

%collect ORN skel IDs from PN3LS hoc file and save them in a txt file
idCommand=['grep -Po ''(?<=^synapse_)\d*'' ', ...
    '/home/simulation/nC_projects/PN2RS_151125/simulations/minis_151130/PN2RS_151125.hoc > /home/simulation/nC_projects/PN2RS_151125/simulations/minis_151130/ornIDs.txt'];
    
system(idCommand);
synIDs=importdata('/home/simulation/nC_projects/PN2RS_151125/simulations/minis_151130/ornIDs.txt');

fireTimeCmd=['grep -Po ''((?<=.start = )\d*)'' ', ...
    '/home/simulation/nC_projects/PN2RS_151125/simulations/minis_151130/PN2RS_151125.hoc > /home/simulation/nC_projects/PN2RS_151125/simulations/minis_151130/ornSpikeTimes.txt'];
system(fireTimeCmd);
fireTimes=importdata('/home/simulation/nC_projects/PN2RS_151125/simulations/minis_151130/ornSpikeTimes.txt');


%% Collect MEPSPs in an array



for o=1:length(synIDs)
    
    somaMini=pn2RS_Vm(find(pn2RS_simTime==fireTimes(o))-40:find(pn2RS_simTime==fireTimes(o))+1000);
    
    somaOverLocal{5}(o)=(max(somaMini)+59.4)/(max(localMinis{5}(o,:))+59.4);
    
    
    
end


%%



figure()
set(gcf, 'Color', 'w')

PN_Names={'PN1LS','PN2LS', 'PN3LS', 'PN1RS', 'PN2RS'};

for i=1:5
    subplot(5,1,i)
%     scatter(i*ones(1,numel(miniAmps{i})),miniAmps{i})
%     
%     hold on

hist(somaOverLocal{i},250)
 xlim([0 .3])
title(PN_Names(i),'FontSize',12)

if i==5
    
    xlabel('mini amp at soma/local mini amp','FontSize',16)
    ylabel('Freq','FontSize',16)
    
else
end



end


