
leftORNSubset=[337396,401197,492811,320688,699676];
rightORNSubset=[360235,362982,332797,379044,362999];
ORNs=[leftORNSubset, rightORNSubset];

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

%return all skeleton IDs of DM6 PNs
PNs=sort(annotations.DM6_0x20_PN);

%Load the connector structure
load('~/tracing/conns.mat')

%gen conn fieldname list
connFields=fieldnames(conns);

load('aveSizesBC.mat')

edgeNums=[];
counter=1;

for o=1:10
    for p=1:5
        
        
        ornID=ORNs(o);
        pnID=PNs(p);
        
        connArray=aveSizesBC{o,p};
        numConnSyns=size(connArray,1);
        
        connEdgeCount=0;
        
        for c=1:length(connFields)
            conn=connFields(c);
            
            pre=conns.(cell2mat(conn)).pre;
            post=conns.(cell2mat(conn)).post;
            
            if isempty(pre)==0
                
                if pre == ornID && ismember(pnID,post)==1
                    
                    connEdgeCount=connEdgeCount+sum(ismember(post,pnID));
                    
                else
                end
            else
            end
        end
        
      edgeNums(counter,:)=[numConnSyns,connEdgeCount]; 
      counter=counter+1
        
    end
end