%% Load annotations and connectors


% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;

ORNs=[ORNs_Left, ORNs_Right];

%return all skeleton IDs of DM6 PNs
% PNs=annotations.PN;
PNs=sort(annotations.DM6_0x20_PN);
% PNs=annotations.DM6_0x20_PN;

% return all skel IDs with *LN* in fieldname
Fn = fieldnames(annotations);
selFn = Fn(~cellfun(@isempty,regexp(Fn,'LN')));

LNs=[];
for i = 1:numel(selFn)
    LNs=[LNs, annotations.(selFn{i})];
end

LNs = unique(LNs);

%
% LNs=annotations.LN;
% LNs=[LNs, annotations.potential_0x20_LN];
% LNs=[LNs, annotations.Prospective_0x20_LN];
% LNs=[LNs, annotations.Likely_0x20_LN];


%Load the connector structure
load('~/tracing/conns.mat')

%gen conn fieldname list
connFields=fieldnames(conns);


%%

numPostPNL=[];
numPostNonPNL=[];

numPostPNR=[];
numPostNonPNR=[];


for c = 1:length(connFields)
    
    curConnID=cell2mat(connFields(c));
    
    %Make sure the connector doesnt have an empty presynaptic field
    if isempty(conns.(curConnID).pre) == 1
        
        %or an empty postsynaptic field, if its empty it will be a cell
    elseif iscell(conns.(curConnID).post) == 1
        
    else
        
        pre=conns.(curConnID).pre;
        post=conns.(curConnID).post;
        
        if ismember(pre,ORNs)==1 && sum(ismember(post,PNs))>0
            
            if ismember(max(find(ismember(PNs, post))),[1,2,5]) == 1
                
                numPostNonPNL=[numPostNonPNL,numel(post)-sum(ismember(post,PNs))];
                numPostPNL=[numPostPNL,sum(ismember(post,PNs))];
                
            else
                
                numPostNonPNR=[numPostNonPNR,numel(post)-sum(ismember(post,PNs))];
                numPostPNR=[numPostPNR,sum(ismember(post,PNs))];
                
            end
        else
        end
    end
    
    
    
end

%%
figure('units','normalized','outerposition',[0 0 1 1])
set(gcf,'Color','w')

edges=[0.5:1:7.5];
subplot(1,2,1)
histogram(numPostPNL, 'BinEdges',edges,'Normalization','probability')
hold on
histogram(numPostPNR, 'BinEdges',edges,'Normalization','probability')
box off
ylabel('Probability')
xlabel('# Postsynaptic PN Profiles')
%legend({'Left Glomerulus','Right Glomerulus'})
ylim([0 .6])
xlim([0 10])
set(gca,'FontSize',18)
set(gca,'TickDir','out')
axis square


edges=[0.5:1:9.5];
subplot(1,2,2)
histogram(numPostNonPNL, 'BinEdges',edges,'Normalization','probability')
hold on
histogram(numPostNonPNR, 'BinEdges',edges,'Normalization','probability')
legend({'Left Glomerulus','Right Glomerulus'})
box off
%ylabel('Probability')
xlabel('# Postsynaptic Non-PN Profiles')
ylim([0 .6])
xlim([0 10])
set(gca,'FontSize',18)
set(gca,'TickDir','out')
axis square


saveas(gcf,'lRPostNumID','epsc')
saveas(gcf,'lRPostNumID')


