#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/william/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/william/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/william/nC_projects/PN2RS/generatedNEURON/x86_64/.libs/libnrnmech.so" "$@"
