
function [] = getPNConnNums(pnNum)

addpath(genpath('/home/wft2/Matlab'));

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;

ORNs=[ORNs_Left, ORNs_Right];

%return all skeleton IDs of DM6 PNs
PNs=sort(annotations.DM6_0x20_PN);


% return all skel IDs with *LN* in fieldname
Fn = fieldnames(annotations);
selFn = Fn(~cellfun(@isempty,regexp(Fn,'LN')));

LNs=[];

for i = 1:numel(selFn)
    LNs=[LNs, annotations.(selFn{i})];
end

LNs = unique(LNs);

%Load the connector structure
load('~/tracing/conns.mat')

%gen conn fieldname list
connFields=fieldnames(conns);


  
    % get contact number between each PN and each PN
    %loop over PNs
    for p=1:length(PNs)
        
        pnToPn(p)=getSynapseNum(PNs(pnNum),PNs(p));
    end
    
    % get contact number between each PN and each LN
    %loop over LNs
    for l=1:length(LNs)
        
        pnToLn(l)=getSynapseNum(PNs(pnNum),LNs(l));
    end
    
    
    % get contact number between each PN and each ORN
    %loop over ORNs
    for orn=1:length(ORNs)
        
        pnToOrn(orn)=getSynapseNum(PNs(pnNum),ORNs(orn));
    end
    
    
    
cd('~/tracing/connectionNums/PNs/')

save([num2str(PNs(pnNum)),'_ToPNs'],'pnToPn')
save([num2str(PNs(pnNum)),'_ToORNs'],'pnToOrn')    
save([num2str(PNs(pnNum)),'_ToLNs'],'pnToLn')    

end