%% Load annotations and connectors

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;

%exclude unilateral ORNs for now

ORNs_Right(find(ORNs_Right == 499879))=[];
ORNs_Left(find(ORNs_Left == 426230))=[];
ORNs_Left(find(ORNs_Left == 401378))=[];
% 
% %exclude ORN 8 because it was temporarily unilateral on 8/5 for testing 
% ORNs_Left(find(ORNs_Left == 593865))=[];

%return all skeleton IDs of DM6 PNs
PNs=annotations.PN;

%Load the connector structure
load('~/tracing/conns.mat')

%gen conn fieldname list
connFields=fieldnames(conns);

%% How Divergent are ORN Output synapses?


% Loop over L ORNs
for o=1:length(ORNs_Left)
    
   
   synCounter=1;
    
    %loop over all connectors
    for i= 1 : length(connFields)
        
        %Make sure the connector doesnt have an empty pre or post-synaptic field
        if isempty(conns.(cell2mat(connFields(i))).pre) == 1 || isempty(conns.(cell2mat(connFields(i))).post) == 1
            
        else
            
            %Check to see if the working skel is presynaptic at this connector
            if conns.(cell2mat(connFields(i))).pre == ORNs_Left(o)
                 numPostL{o}(synCounter)=length(conns.(cell2mat(connFields(i))).post);
                 synCounter=synCounter+1;
           
              
            else
                
            end
        end
        
    end
    

end


% Loop over L ORNs
for o=1:length(ORNs_Right)
    
   
   synCounter=1;
    
    %loop over all connectors
    for i= 1 : length(connFields)
        
        %Make sure the connector doesnt have an empty pre or post-synaptic field
        if isempty(conns.(cell2mat(connFields(i))).pre) == 1 || isempty(conns.(cell2mat(connFields(i))).post) == 1
            
        else
            
            %Check to see if the working skel is presynaptic at this connector
            if conns.(cell2mat(connFields(i))).pre == ORNs_Right(o)
                 numPostR{o}(synCounter)=length(conns.(cell2mat(connFields(i))).post);
                 synCounter=synCounter+1;
           
              
            else
                
            end
        end
        
    end
    

end

sumDivL=[];
sumDivR=[];

for j=1:25
    sumDivL=[sumDivL numPostL{o}];
    sumDivR=[sumDivR numPostR{o}];
end

figure()
set(gcf, 'color', 'w')

subplot(1,2,1)
hist(sumDivL, 20)
xlabel('Num Post-Synaptic Profiles')
ylabel('Freq')
title('Left ORNs')
xlim([0 10])


subplot(1,2,2)
hist(sumDivR, 20)
xlabel('Num Post-Synaptic Profiles')
ylabel('Freq')
title('Right ORNs')
xlim([0 10])


  