%% Load annotations

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;

%exclude unilateral ORNs for now

ORNs_Right(find(ORNs_Right == 499879))=[];
ORNs_Left(find(ORNs_Left == 426230))=[];
ORNs_Left(find(ORNs_Left == 401378))=[];
% 
% %exclude ORN 8 because it was temporarily unilateral on 8/5 for testing 
% ORNs_Left(find(ORNs_Left == 593865))=[];

%return all skeleton IDs of DM6 PNs
PNs=annotations.PN;


%% ORN outputs in DM6 Hist of number of ORN output synapses 


%Load the connector structure
load('~/tracing/conns.mat')

%gen conn fieldname list
connFields=fieldnames(conns);

% Loop over L ORNs
for o=1:length(ORNs_Left)
    
synCounter=0;

%loop over all connectors
for i= 1 : length(connFields)
    
    %Make sure the connector doesnt have an empty presynaptic field
    if isempty(conns.(cell2mat(connFields(i))).pre) == 1
        
    else
        
        %Check to see if the working skel is presynaptic at this connector
        if conns.(cell2mat(connFields(i))).pre == ORNs_Left(o)


                synCounter=synCounter+1;
                
          
        else
        end
    end
end

sumLeftORNOuts(o)=synCounter;

end


% Loop over R ORNs
for o=1:length(ORNs_Right)
    
synCounter=0;

%loop over all connectors
for i= 1 : length(connFields)
    
    %Make sure the connector doesnt have an empty presynaptic field
    if isempty(conns.(cell2mat(connFields(i))).pre) == 1
        
    else
        
        %Check to see if the working skel is presynaptic at this connector
        if conns.(cell2mat(connFields(i))).pre == ORNs_Right(o)


                synCounter=synCounter+1;
                
          
        else
        end
    end
end

sumRightORNOuts(o)=synCounter;

end

figure()
set(gcf, 'color', 'w')

subplot(1,2,1)
hist(sumLeftORNOuts, 20)
xlabel('Num Output Synapses')
ylabel('Freq')
title('Left ORNs')
xlim([40 110])
ylim([0 6])
meanOutL=['Mean: ', num2str(mean(sumLeftORNOuts))];
stdOutL=['std: ', num2str(std(sumLeftORNOuts))];
cvOutL=['CV: ', num2str(std(sumLeftORNOuts)/mean(sumLeftORNOuts))];
text(45,5.5,meanOutL)
text(45,5.25,stdOutL)
text(45,5,cvOutL)


subplot(1,2,2)
hist(sumRightORNOuts, 20)
xlabel('Num Output Synapses')
ylabel('Freq')
title('Right ORNs')
xlim([40 110])
ylim([0 6])
meanOutR=['Mean: ', num2str(mean(sumRightORNOuts))];
stdOutR=['std: ', num2str(std(sumRightORNOuts))];
cvOutR=['CV: ', num2str(std(sumRightORNOuts)/mean(sumRightORNOuts))];
text(45,5.5,meanOutR)
text(45,5.25,stdOutR)
text(45,5,cvOutR)