%% The purpose of this piece of code is to examine the relationship between axon length within a glomerulus and mean fractional input to PNs

%% Load annotations and connectors

% Load annotations json. Generated by Wei's code gen_annotation_map.py
annotations=loadjson('~/tracing/sid_by_annotation.json');

% Return all skeleton IDs for R and L ORNs

ORNs_Left=annotations.Left_0x20_ORN;
ORNs_Right=annotations.Right_0x20_ORN;

%exclude unilateral ORNs for now

ORNs=[ORNs_Left, ORNs_Right];

%return all skeleton IDs of DM6 PNs
PNs=annotations.DM6_0x20_PN;


%Load the axon length and presynaptic site number data
load('~/Documents/MATLAB/tracingCode2/currentWfly1ManuscriptFigures/ornOutputSynDensity/leftAxons')
load('~/Documents/MATLAB/tracingCode2/currentWfly1ManuscriptFigures/ornOutputSynDensity/rightAxons')


% For each ORN calculate its total ipsi within glomerulus length 

for p=1:length(ORNs)
    
    leftRunL=[];
    leftRunPS=[];
    
    
    for j=1:size(leftAxons{p},2)
        
        leftRunL=[leftRunL, leftAxons{p}(1,j)];
        leftRunPS=[leftRunPS,leftAxons{p}(2,j)];
        
    end
    
    leftLengths(p)=sum(leftRunL);
    leftPreSites(p)=sum(leftRunPS);
    
    
    rightRunL=[];
    rightRunPS=[];
    
    
    for j=1:size(rightAxons{p},2)
        rightRunL=[rightRunL, rightAxons{p}(1,j)];
        rightRunPS=[rightRunPS,rightAxons{p}(2,j)];
    end
    
    rightLengths(p)=sum(rightRunL);
    rightPreSites(p)=sum(rightRunPS);
    
end



%% Calculate fractional input values 

%Load ornToPn contact Num matrix
load('~/Documents/MATLAB/tracingCode2/wfly1_Manuscript_Archive16March2016/ornToPn.mat');
    

% Now divide each element by the sum of the column it is in
contactNum_Fract=zeros(53,5);

for c=1:5
    
    contactNum_Fract(1:27,c)=ornsToPn(1:27,c)./sum(ornsToPn(1:27,c));
    contactNum_Fract(28:end,c)=ornsToPn(28:end,c)./sum(ornsToPn(28:end,c));
    
end


%% Cable length V Fractional PN input Right Axons

%combine axon length and mean fractional input to PNs in one array, remove
%rows corresponding to unilateral ORNs in the hemisphere they neglect 

rightAxonLenFracts=[];
rightAxonLenFracts(:,1)=rightLengths;
rightAxonLenFracts(:,2)=mean(contactNum_Fract(:,[3,4])');
rightAxonLenFracts(find(isnan(rightAxonLenFracts(:,1))),:)=[];


leftAxonLenFracts=[];
leftAxonLenFracts(:,1)=leftLengths;
leftAxonLenFracts(:,2)=mean(contactNum_Fract(:,[1,2,5])');
leftAxonLenFracts(find(isnan(leftAxonLenFracts(:,1))),:)=[];


%% Plotting, all ORNs in each hemisphere

figure()
set(gcf, 'Color', 'w')

scatter(leftAxonLenFracts(:,1),leftAxonLenFracts(:,2), 'filled')
hold on
scatter(rightAxonLenFracts(:,1),rightAxonLenFracts(:,2)  ,'r', 'filled')


xlabel('Cable Length (nm)', 'FontSize', 16)
ylabel('Fractional Input', 'FontSize',16)
ax=gca;
ax.FontSize=16;
xlim([0.4*10^5 1.8*10^5])
ylim([0.005 0.065])

legend({'Right Glom','Left Glom'}, 'FontSize', 16, 'Location', 'NorthWest')

%Statistics

[pRho, pP]=corr([leftAxonLenFracts(:,1);rightAxonLenFracts(:,1)], [leftAxonLenFracts(:,2);rightAxonLenFracts(:,2)])
text(1*10^5,.012,{['Pearson''s R val: ', num2str(pRho)]; ['Pearson''s P val: ', num2str(pP)]}, 'FontSize', 16)

saveas(gcf,'axonLengthVFractInput')


%% Plotting broken out by ORN population and hemisphere

figure()
subplot(2,2,1)
set(gcf, 'Color', 'w')
scatter(leftAxonLenFracts(1:27,1),leftAxonLenFracts(1:27,2), 'filled')
xlabel('Cable Length')
ylabel('Mean Fractional Input')
xlim([0.4*10^5 1.8*10^5])
ylim([0.005 0.065])
title('Left Glomerulus')
legend({'Left ORNs'}, 'Location', 'NorthWest')

%Statistics
[pRho, pP]=corr(leftAxonLenFracts(1:27,1),leftAxonLenFracts(1:27,2), 'type','Spearman')
text(1.2*10^5,.02,{['Spearman''s R val: ', num2str(pRho)]; ['Spearman''s P val: ', num2str(pP)]})



subplot(2,2,2)
set(gcf, 'Color', 'w')
scatter(leftAxonLenFracts(28:end,1),leftAxonLenFracts(28:end,2), 'r','filled')
xlabel('Cable Length')
ylabel('Mean Fractional Input')
xlim([0.4*10^5 1.8*10^5])
ylim([0.005 0.065])
title('Left Glomerulus')
legend({'Right ORNs'}, 'Location', 'NorthWest')

%Statistics
[pRho, pP]=corr(leftAxonLenFracts(28:end,1),leftAxonLenFracts(28:end,2), 'type','Spearman')
text(1.2*10^5,.02,{['Spearman''s R val: ', num2str(pRho)]; ['Spearman''s P val: ', num2str(pP)]})


subplot(2,2,3)
set(gcf, 'Color', 'w')
scatter(rightAxonLenFracts(1:27,1),rightAxonLenFracts(1:27,2), 'filled')
xlabel('Cable Length')
ylabel('Mean Fractional Input')
xlim([0.4*10^5 1.8*10^5])
ylim([0.005 0.065])
title('Right Glomerulus')
legend({'Left ORNs'}, 'Location', 'NorthWest')

%Statistics
[pRho, pP]=corr(rightAxonLenFracts(1:27,1),rightAxonLenFracts(1:27,2), 'type','Spearman')
text(1.2*10^5,.02,{['Spearman''s R val: ', num2str(pRho)]; ['Spearman''s P val: ', num2str(pP)]})


subplot(2,2,4)
set(gcf, 'Color', 'w')
scatter(rightAxonLenFracts(28:end,1),rightAxonLenFracts(28:end,2),'r', 'filled')
xlabel('Cable Length')
ylabel('Mean Fractional Input')
xlim([0.4*10^5 1.8*10^5])
ylim([0.005 0.065])
title('Right Glomerulus')
legend({'Right ORNs'}, 'Location', 'NorthWest')

%Statistics

[pRho, pP]=corr(rightAxonLenFracts(28:end,1),rightAxonLenFracts(28:end,2), 'type','Spearman')
text(1.2*10^5,.02,{['Spearman''s R val: ', num2str(pRho)]; ['Spearman''s P val: ', num2str(pP)]})


saveas(gcf,'axonLengthVFractInput_brokenOut')



